views/menu_web.py
from flask import Blueprint

menu_web = Blueprint('menu_web', __name__)


@menu_web.route('/', methods=["GET"])
def menu():
    return "menu"


@menu_web.route('/edit', methods=["GET"])
def edit_menu():
    return "edit menu"


@menu_web.route('/item/new', methods=["GET"])
def new_item():
    return "new item"


@menu_web.route('/item/<id>/edit', methods=["GET"])
def edit_item(id):
    return "edit item"


@menu_web.route('/combo/new', methods=["GET"])
def new_combo():
    return "new combo"


@menu_web.route('/combo/<id>/edit', methods=["GET"])
def edit_combo(id):
    return "edit combo"

views/order_web.py
from datetime import datetime, timedelta

from flask import Blueprint, render_template

from flask_login import current_user

from lib.auth import admin_required

order_web = Blueprint("order_web", __name__)

time_format = '%Y-%m-%dT%H:%M'


@order_web.route("/new", methods=["GET"])
def cart():
    return "cart"


@order_web.route("/history", methods=["GET"])
@admin_required
def history():
    begin = (datetime.now()-timedelta(days=7)).strftime(time_format)
    end = datetime.now().strftime(time_format)
    return render_template('history.html', auth=current_user.role, name=current_user.name, begin=begin, end=end) # noqa


@order_web.route("/pending", methods=["GET"])
def pending():
    return "pending"


@order_web.route("/todo", methods=["GET"])
def todo():
    return "todo"


@order_web.route("/state", methods=["GET"])
def state():
    return "state"

views/setting_web.py
from flask import Blueprint

setting_web = Blueprint('setting_web', __name__)


@setting_web.route('/business-time', methods=["GET"])
def business_time():
    return "business time"

views/user_web.py
from flask import Blueprint, redirect, url_for

from flask_login import logout_user

user_web = Blueprint('user_web', __name__)


@user_web.route('/logout', methods=["GET"])
def logout():
    logout_user()
    return redirect(url_for('menu_web.menu'))


@user_web.route('/password/reset', methods=["GET"])
def reset_password():
    return "reset password"


@user_web.route('/password/forget', methods=["GET"])
def forget_password():
    return "forget password"


@user_web.route('/profile/<id>', methods=["GET"])
def profile(id):
    return "profile"

templates/component/login.html
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">登入</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="login-form" action="#">
                    <div class="form-group">
                        <label for="login-user-name" class="col-form-label">帳號:</label>
                        <input type="text" class="form-control" id="login-user-name" required>
                    </div>
                    <div class="form-group">
                        <label for="login-password" class="col-form-label">密碼:</label>
                        <input type="password" class="form-control" id="login-password" required>
                        <small id="login-wrong" class="form-text wrong-msg">　</small>
                    </div>
                    <button type="submit" class="btn btn-primary" id="login">登入</button>
                </form>
            </div>
            <div class="modal-footer">
                <a href="{{ url_for('user_web.forget_password') }}">忘記密碼</a>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="login-frozen-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">帳號凍結</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>您的帳號被凍結，將無法使用訂餐功能</p>
            </div>
        </div>
    </div>
</div>

templates/component/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Ton80</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% if url == "customer" %}
        <li class="nav-item {{ 'active' if active_page == 'menu' else '' }}">
            <a class="nav-link" href="{{ url_for('menu_web.menu') }}">菜單</a>
        </li>
        <li class="nav-item {{ 'active' if active_page == 'cart' else '' }}">
            <a class="nav-link" href="{{ url_for('order_web.cart') }}">點菜單(購物車)</a>
        </li>
        {% if auth != "anonymous" %}
        <li class="nav-item {{ 'active' if active_page == 'order_state' else '' }}">
            <a class="nav-link" href="{{ url_for('order_web.state') }}">訂單狀態</a>
        </li>
        {% endif %}
      {% else %}
        <li class="nav-item {{ 'active' if active_page == 'order' else '' }}">
          <a class="nav-link" href="{{ url_for('order_web.pending')}}">顧客點餐</a>
        </li>
        <li class="nav-item {{ 'active' if active_page == 'todo' else '' }}">
          <a class="nav-link" href="{{ url_for('order_web.todo') }}">餐點製作清單</a>
        </li>
        <li class="nav-item {{ 'active' if active_page == 'history' else '' }}">
          <a class="nav-link" href="{{ url_for('order_web.history') }}">歷史點菜單</a>
        </li>
        <li class="nav-item {{ 'active' if active_page == 'menu-edit' else '' }}">
          <a class="nav-link" href="{{ url_for('menu_web.edit_menu') }}">編輯菜單</a>
        </li>
      {% endif %}
    </ul>
    <ul class="navbar-nav ml-auto">
    {% if auth == "anonymous" %}
      <li class="nav-item active">
          <a class="nav-link" href="#login-modal" data-toggle="modal">登入</a>
      </li>
      <li class="nav-item active">
          <a class="nav-link" href="#register-modal" data-toggle="modal">註冊</a>
      </li>
    {% else %}
        <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('user_web.logout') }}">登出</a>
        </li>
        <li class="nav-item active dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
                你好 {{name}}
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{{ url_for('user_web.profile', id=id) }}">個人資料</a>
                {% if auth == "admin" %}
                    <a class="dropdown-item" href="{{ url_for('order_web.pending') }}">管理頁面</a>
                    <a class="dropdown-item" href="{{ url_for('setting_web.business_time') }}">設定點餐時間</a>
                {% endif %}
            </div>
        </li>
    {% endif %}
    </ul>
  </div>
</nav>

templates/component/register.html
<div class="modal fade" id="register-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">註冊</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="register-form" action="#">
                    <div class="form-group">
                        <label for="register-user-name">帳號:</label>
                        <input type="text" class="form-control" id="register-user-name" required>
                    </div>
                    <div class="form-group">
                        <label for="register-password">密碼:</label>
                        <input type="password" class="form-control" id="register-password" required minlength="8">
                    </div>
                    <div class="form-group">
                        <label for="register-confirm-password">確認密碼:</label>
                        <input type="password" class="form-control" id="register-confirm-password" required minlength="8">
                    </div>
                    <div class="form-group">
                        <label for="register-age">年齡:</label>
                        <input type="number" class="form-control" id="register-age" min="0" required>
                    </div>
                    <div class="form-group">
                        <label for="register-gender">性別:</label>
                        <select id="register-gender" class="form-control" required>
                            <option value="male">男</option>
                            <option value="female">女</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="register-phone">手機:</label>
                        <input type="tel" class="form-control" id="register-phone" maxlength="10" minlength="10" required>
                    </div>
                    <div class="form-group">
                        <label for="register-email">Email:</label>
                        <input type="email" class="form-control" id="register-email" required>
                        <small id="register-wrong" class="form-text wrong-msg">　</small>
                    </div>
                    <button type="submit" class="btn btn-primary" id="register">註冊</button>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="register-success-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">註冊成功</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>恭喜您註冊成功</p>
            </div>
        </div>
    </div>
</div>